"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StreamHelper = exports.Guid = exports.ArrayHelper = exports.UsingAsync = exports.InitSettingManager = exports.SettingManager = exports.SETTING_INJECT_TOKEN = exports.RegisterModule = exports.GetModuleDepends = exports.GetModulePath = exports.DependsOn = exports.ModulePath = exports.RegisterModuleByPath = exports.StopModule = exports.StartModule = exports.AppModule = exports.MODULE_PATH_METADATA_TOKEN = exports.MODULE_INJECT_TOKEN = exports.GetMetadata = exports.DefineMetadata = exports.Metadata = exports.GetMetadataKey = exports.EventHandler = exports.IsEventHandler = exports.GetEventKey = exports.EventKey = exports.EVENT_HANDLER_METADATA = exports.EventBus = exports.EVENT_BUS_INJECT_TOKEN = exports.UserFriendlyError = exports.NewbilityError = exports.InitServiceLoader = exports.InitServiceCollection = exports.ServiceCollection = exports.SC_INJECT_TOKEN = exports.InitLogger = exports.Logger = exports.LOGGER_INJECT_TOKEN = exports.GetInjectToken = exports.IsAbstract = exports.Abstract = exports.IsMultipleRegister = exports.AllowMultiple = exports.ReplaceService = exports.GetInjectInfo = exports.Inject = exports.Injectable = exports.Transient = exports.Singleton = exports.Container = void 0;
exports.CoreModule = void 0;
require("reflect-metadata");
const Dependency_1 = require("./src/di/Dependency");
Object.defineProperty(exports, "Abstract", { enumerable: true, get: function () { return Dependency_1.Abstract; } });
Object.defineProperty(exports, "AllowMultiple", { enumerable: true, get: function () { return Dependency_1.AllowMultiple; } });
Object.defineProperty(exports, "Container", { enumerable: true, get: function () { return Dependency_1.Container; } });
Object.defineProperty(exports, "GetInjectInfo", { enumerable: true, get: function () { return Dependency_1.GetInjectInfo; } });
Object.defineProperty(exports, "GetInjectToken", { enumerable: true, get: function () { return Dependency_1.GetInjectToken; } });
Object.defineProperty(exports, "Inject", { enumerable: true, get: function () { return Dependency_1.Inject; } });
Object.defineProperty(exports, "Injectable", { enumerable: true, get: function () { return Dependency_1.Injectable; } });
Object.defineProperty(exports, "IsAbstract", { enumerable: true, get: function () { return Dependency_1.IsAbstract; } });
Object.defineProperty(exports, "IsMultipleRegister", { enumerable: true, get: function () { return Dependency_1.IsMultipleRegister; } });
Object.defineProperty(exports, "ReplaceService", { enumerable: true, get: function () { return Dependency_1.ReplaceService; } });
Object.defineProperty(exports, "Singleton", { enumerable: true, get: function () { return Dependency_1.Singleton; } });
Object.defineProperty(exports, "Transient", { enumerable: true, get: function () { return Dependency_1.Transient; } });
const ServiceCollection_1 = require("./src/di/ServiceCollection");
Object.defineProperty(exports, "SC_INJECT_TOKEN", { enumerable: true, get: function () { return ServiceCollection_1.SC_INJECT_TOKEN; } });
Object.defineProperty(exports, "ServiceCollection", { enumerable: true, get: function () { return ServiceCollection_1.ServiceCollection; } });
Object.defineProperty(exports, "InitServiceCollection", { enumerable: true, get: function () { return ServiceCollection_1.InitServiceCollection; } });
const NewbilityError_1 = require("./src/error/NewbilityError");
Object.defineProperty(exports, "NewbilityError", { enumerable: true, get: function () { return NewbilityError_1.NewbilityError; } });
const UserFriendlyError_1 = require("./src/error/UserFriendlyError");
Object.defineProperty(exports, "UserFriendlyError", { enumerable: true, get: function () { return UserFriendlyError_1.UserFriendlyError; } });
const EventBus_1 = require("./src/event/EventBus");
Object.defineProperty(exports, "EventBus", { enumerable: true, get: function () { return EventBus_1.EventBus; } });
Object.defineProperty(exports, "EVENT_BUS_INJECT_TOKEN", { enumerable: true, get: function () { return EventBus_1.EVENT_BUS_INJECT_TOKEN; } });
const EventHandler_1 = require("./src/event/EventHandler");
Object.defineProperty(exports, "EVENT_HANDLER_METADATA", { enumerable: true, get: function () { return EventHandler_1.EVENT_HANDLER_METADATA; } });
Object.defineProperty(exports, "EventKey", { enumerable: true, get: function () { return EventHandler_1.EventKey; } });
Object.defineProperty(exports, "GetEventKey", { enumerable: true, get: function () { return EventHandler_1.GetEventKey; } });
Object.defineProperty(exports, "IsEventHandler", { enumerable: true, get: function () { return EventHandler_1.IsEventHandler; } });
Object.defineProperty(exports, "EventHandler", { enumerable: true, get: function () { return EventHandler_1.EventHandler; } });
const Logger_1 = require("./src/logger/Logger");
Object.defineProperty(exports, "LOGGER_INJECT_TOKEN", { enumerable: true, get: function () { return Logger_1.LOGGER_INJECT_TOKEN; } });
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return Logger_1.Logger; } });
Object.defineProperty(exports, "InitLogger", { enumerable: true, get: function () { return Logger_1.InitLogger; } });
const Metadata_1 = require("./src/metadata/Metadata");
Object.defineProperty(exports, "DefineMetadata", { enumerable: true, get: function () { return Metadata_1.DefineMetadata; } });
Object.defineProperty(exports, "GetMetadata", { enumerable: true, get: function () { return Metadata_1.GetMetadata; } });
Object.defineProperty(exports, "GetMetadataKey", { enumerable: true, get: function () { return Metadata_1.GetMetadataKey; } });
Object.defineProperty(exports, "Metadata", { enumerable: true, get: function () { return Metadata_1.Metadata; } });
const AppModule_1 = require("./src/modularity/AppModule");
Object.defineProperty(exports, "AppModule", { enumerable: true, get: function () { return AppModule_1.AppModule; } });
Object.defineProperty(exports, "StartModule", { enumerable: true, get: function () { return AppModule_1.StartModule; } });
Object.defineProperty(exports, "StopModule", { enumerable: true, get: function () { return AppModule_1.StopModule; } });
Object.defineProperty(exports, "RegisterModuleByPath", { enumerable: true, get: function () { return AppModule_1.RegisterModuleByPath; } });
Object.defineProperty(exports, "ModulePath", { enumerable: true, get: function () { return AppModule_1.ModulePath; } });
Object.defineProperty(exports, "GetModulePath", { enumerable: true, get: function () { return AppModule_1.GetModulePath; } });
Object.defineProperty(exports, "GetModuleDepends", { enumerable: true, get: function () { return AppModule_1.GetModuleDepends; } });
Object.defineProperty(exports, "RegisterModule", { enumerable: true, get: function () { return AppModule_1.RegisterModule; } });
Object.defineProperty(exports, "MODULE_INJECT_TOKEN", { enumerable: true, get: function () { return AppModule_1.MODULE_INJECT_TOKEN; } });
Object.defineProperty(exports, "MODULE_PATH_METADATA_TOKEN", { enumerable: true, get: function () { return AppModule_1.MODULE_PATH_METADATA_TOKEN; } });
const SettingManager_1 = require("./src/setting/SettingManager");
Object.defineProperty(exports, "SETTING_INJECT_TOKEN", { enumerable: true, get: function () { return SettingManager_1.SETTING_INJECT_TOKEN; } });
Object.defineProperty(exports, "SettingManager", { enumerable: true, get: function () { return SettingManager_1.SettingManager; } });
Object.defineProperty(exports, "InitSettingManager", { enumerable: true, get: function () { return SettingManager_1.InitSettingManager; } });
const Disposable_1 = require("./src/sys/Disposable");
Object.defineProperty(exports, "UsingAsync", { enumerable: true, get: function () { return Disposable_1.UsingAsync; } });
const ArrayHelper_1 = require("./src/util/ArrayHelper");
Object.defineProperty(exports, "ArrayHelper", { enumerable: true, get: function () { return ArrayHelper_1.ArrayHelper; } });
const Guid_1 = require("./src/util/Guid");
Object.defineProperty(exports, "Guid", { enumerable: true, get: function () { return Guid_1.Guid; } });
const StreamHelper_1 = require("./src/util/StreamHelper");
Object.defineProperty(exports, "StreamHelper", { enumerable: true, get: function () { return StreamHelper_1.StreamHelper; } });
const DependsOn_1 = require("./src/modularity/DependsOn");
Object.defineProperty(exports, "DependsOn", { enumerable: true, get: function () { return DependsOn_1.DependsOn; } });
const ServiceLoader_1 = require("./src/di/ServiceLoader");
Object.defineProperty(exports, "InitServiceLoader", { enumerable: true, get: function () { return ServiceLoader_1.InitServiceLoader; } });
const CoreModule_1 = require("./src/CoreModule");
Object.defineProperty(exports, "CoreModule", { enumerable: true, get: function () { return CoreModule_1.CoreModule; } });
//# sourceMappingURL=index.js.map